### PR TITLE
Content: New Earthrise Newsletter for STEM story

### PR DESCRIPTION
**Pull request by agurvich**
## Adding content

Add new content requested by Ellen Gray for OCOMM newsletter Earthrise.

---

## Content checklist

Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) for more details.

### Any content
- [x] Cover image with proper attribution (when relevant) is present.
- [x] Cover images do not contain any text (they're used as a background and text may not be readable).
- [x] All images are not too big/heavy. As a general rule of thumb, they should not weigh more than 500KB, or be larger than 2000px. See the [media guide](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/media.md#media) for more info.
- [x] Content was added using the available [MDX Blocks](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/MDX_BLOCKS.md).

### Datasets
- [ ] [Layer description](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/layer.md#properties) is defined.
- [ ] [Layer legend](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/layer.md#legend) is setup.
- [ ] The Dataset is showing up on the map correctly

### Stories
- [x] [Publication date](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md#stories) value is set

### CODE REVIEW

**Comment by agurvich** [comment]
@j08lue help me out here-- how did main end up 5 commits ahead of develop? Do you want me to redo this but base off develop instead of main? It's been a hot second since I've tried to push any content so maybe I am doing it wrong.

**Comment by j08lue** [comment]
> how did main end up 5 commits ahead of develop

I won't try to diagnose past Git flows now, but this branch here does not have any merge conflicts with it's target `develop`, so I recommend to merge it if it is ready and take it from there. No need to rebase or any other magic.

**Review by j08lue — APPROVED** [review]
The link to the Earthrise Newsletter looks as I would expect and points to a valid source. 
image

As far as I can tell, this is good to go.

@agurvich, can you confirm, please?

**Comment by agurvich** [comment]
Yes this looks correct to me! Thank you for approving a PR from vacation but go relax or something!

**Pull request merged**
