### PR TITLE
remove tagline from GHGC

### PR DESCRIPTION
**Pull request by freitagb**
## Why are you creating this Pull Request?

- [Adding Datasets or Stories](?title=Content%3A%20%3Cname%3E&expand=1&template=content.md)
- [Version Release](?title=Deploy%20vX.X.X&expand=1&template=version_release.md)
- [Other](?expand=1&template=default.md)

### CODE REVIEW

**Comment by freitagb** [comment]
A couple of notes for when you review this PR @dzole0311 @amarouane-ABDELHAK @j08lue 

Currently the carousel doesn't support text on background images so the text is baked onto the images themselves. This PR removes the GHGC tagline in the carousel as Deborah requested

Other changes in this PR include renaming of sea level rise to sea level change throughout the Earth.gov site as was requested by Nadya at HQ. I believe I've caught all of them but let me know if any were missed.

**Review by amarouane-ABDELHAK — APPROVED** [review]
LGTM

**Review by j08lue — APPROVED** [review]
Looks good to me and all the renamed Sea Level Change resources seem to work as expected.

**Review by dzole0311 — APPROVED** [review]
Looks good to me as well!

> Currently the carousel doesn't support text on background images so the text is baked onto the images themselves

@freitagb I created a quick showcase to test adding text dynamically over the images. It’s definitely doable with a few tweaks if this is something we want (though I believe the original intention was to avoid overlaying text directly on the images like [traditional carousels](https://github.com/NASA-IMPACT/veda-ui/issues/1084#issuecomment-2275310605))

Demo: https://deploy-preview-156--earth-information-center.netlify.app/
Changes: https://github.com/NASA-IMPACT/veda-config-eic/pull/156/files

**Pull request merged**
