### PR TITLE
Port the carousel feature to EIC

### PR DESCRIPTION
**Pull request by dzole0311**
This PR introduces the configurable carousel component to the EIC instance. [Example](https://deploy-preview-147--earth-information-center.netlify.app/) of the Carousel shown on the home page.

Usage:

1. The <Carousel> component can be simply imported and used as shown [here](https://github.com/NASA-IMPACT/veda-config-eic/pull/147/files#diff-0e4e8d741403aeb3774c5873685c7a9c24525eccf746c56c408186cb5f0f14f6R115).
2. Each carousel card is customizable through the [config file](https://github.com/NASA-IMPACT/veda-config-eic/pull/148/files#diff-1335d174ce435a4f2cb6cbf16352aee0ad6ea5f9c2bc68c69ce0717bb088bbfb). I've included examples in the config file to showcase linking to internal/external routes and image usage for each card

### CODE REVIEW

**Review by aboydnw — APPROVED** [review]
Seems good to me. I did a quick smoke test of the example you linked and the other functionality in the app and didn't notice anything off.

**Comment by aboydnw** [comment]
@agurvich on Monday we should be able to merge this and you can configure the carousel with content (see @dzole0311 's example linked above) to push up to production

**Comment by amarouane-ABDELHAK** [comment]
Sorry if I am missing something 😅, but I don't see any carousel featured in the preview link https://deploy-preview-148--earth-information-center.netlify.app where should I be looking at 🤔

**Comment by amarouane-ABDELHAK** [comment]
Thank you @aboydnw I see it now. Looks good!

**Pull request merged**
