### PR TITLE
Fix links on home page

### PR DESCRIPTION
**Pull request by j08lue**
- [x] Fix button on GHG Center feature
- [x] Fix "Learn more" link to EIC about page
- [x] Fix link above the GHG Center feature
   image

### CODE REVIEW

**Comment by j08lue** [comment]
The last one, the broken `ExpandLink` I am not sure about how to fix. Stabbing around a bit...

I can see if I can get someone to fix it in the next days, else we'll just remove that link or so, since the users can click on the button of the GHG Center instead.

**Comment by j08lue** [comment]
Yeah, `NavLink` is obviously... a nav link. So this does not work. I guess we need the `a` / as `a` kinda thing...

**Comment by slesaad** [comment]
Looks like `styled.a` works, will need to switch `to=` to `href=`

**Comment by j08lue** [comment]
Not sure what the reason to choose `styled.a` over `NavLink` is, but I can go back to that...

**Comment by j08lue** [comment]
Works with `NavLink`. Should we keep it or change it back to `styled.a`, @slesaad? Your call. 😄

**Comment by slesaad** [comment]
Let's keep it since it's working already! 😄

**Review by slesaad — APPROVED** [review]

**Pull request merged**
