### PR TITLE
Content: Replace images with embedded youtube videos

### PR DESCRIPTION
**Pull request by agurvich**
## Adding content

Replace all of the static images with embedded youtube videos that loop. 

---

## Content checklist

Check the [Content Documentation](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md) for more details.

### Any content
- [x] Cover image with proper attribution (when relevant) is present.
- [x] Cover images do not contain any text (they're used as a background and text may not be readable).
- [x] All images are not too big/heavy. As a general rule of thumb, they should not weigh more than 500KB, or be larger than 2000px. See the [media guide](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/media.md#media) for more info.
- [x] Content was added using the available [MDX Blocks](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/MDX_BLOCKS.md).

### Datasets
- [x] [Layer description](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/layer.md#properties) is defined.
- [x] [Layer legend](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/frontmatter/layer.md#legend) is setup.
- [x] The Dataset is showing up on the map correctly

### Stories
- [x] [Publication date](https://github.com/NASA-IMPACT/veda-ui/blob/main/docs/content/CONTENT.md#stories) value is set

### CODE REVIEW

**Comment by agurvich** [comment]
After seeing the static images I was asked to replace them with some snippets from a longer video.

there's also a request to remove the gray embedding outline so I'm going to raise an issue to add an option on the Embed to hide that frame

**Comment by agurvich** [comment]
https://github.com/NASA-IMPACT/veda-ui/issues/778

**Review by j08lue — APPROVED** [review]
Seems to do what you intended.

IMO the still image version was better than all these busy videos running at the same time. Maybe there could be a way to have stills but a user can easily start the video from them? 🤷 Just my 2ct.

I'd support that we more generally look into ways to integrate videos into our content more elegantly / seamlessly (including revising the embed border).

**Comment by agurvich** [comment]
Re: still images vs. videos, I think it would be cool to have the still image animate on hover but I wasn't sure I could get it to work in a custom component fast enough to meet this Webby deadline. That might be a cool feature to have as a block component (you could provide src for the thumbnail and animation). Maybe limit to gifs below a certain size? It's hard to get a good looking gif that isn't gigantic though...

**Pull request merged**
